version: '3'

services:
  redis-1:
    networks:
      - redis-net
    image: redis
    volumes:
      - type: bind
        source: ./cluster-config.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    deploy:
      resources:
        limits:
          cpus: 0.1

  redis-2:
    networks:
      - redis-net
    image: redis
    volumes:
      - type: bind
        source: ./cluster-config.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    deploy:
      resources:
        limits:
          cpus: 0.1

  redis-3:
    networks:
      - redis-net
    image: redis
    volumes:
      - type: bind
        source: ./cluster-config.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    deploy:
      resources:
        limits:
          cpus: 0.1

  redis-4:
    networks:
      - redis-net
    image: redis
    volumes:
      - type: bind
        source: ./cluster-config.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    deploy:
      resources:
        limits:
          cpus: 0.1

  redis-5:
    networks:
      - redis-net
    image: redis
    volumes:
      - type: bind
        source: ./cluster-config.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    deploy:
      resources:
        limits:
          cpus: 0.1

  redis-6:
    networks:
      - redis-net
    image: redis
    volumes:
      - type: bind
        source: ./cluster-config.conf
        target: /usr/local/etc/redis/redis.conf
    entrypoint: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    deploy:
      resources:
        limits:
          cpus: 0.1

  redis-insight:
    networks:
      - redis-net
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - redisinsight:/db
    deploy:
      resources:
        limits:
          cpus: 0.1

  db:
    image: mysql
    environment:
      MYSQL_USER: open_exam
      MYSQL_PASSWORD: open_exam
      MYSQL_DATABASE: open_exam
      MYSQL_ROOT_PASSWORD: open_exam
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - type: bind
        source: ./../scripts/up.sql
        target: /up.sql
    deploy:
      resources:
        limits:
          cpus: 0.1

volumes:
  redisinsight:
    driver: local
  db:
    driver: local

networks:
  redis-net:
    driver: bridge