name: "plugin-db-service"

on:
  push:
    paths:
      - "plugin-db-service/**"
      - ".github/workflows/plugin-db-service.yaml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17'
      - name: Set GOPATH
        run: GOPATH=.
      - name: Install deps
        run: |-
          go mod download
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
      - name: Install protoc
        uses: abelfodil/protoc-action@v1
        with:
          protoc-version: '3.12.4'
      - name: Build proto files
        run: go run dev/scripts/proto.go -all
      - name: Build
        run: |-
          cd plugin-db-service/src
          go build *
      - name: gofmt
        run: gofmt -w src/*
      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: gofmt
          branch: ${{ github.head_ref }}
